### ISSUE TITLE
How to download pre-training files. thak you

### ISSUE THREAD

**Issue by lijin6** [J4ckLiu/SACP#1]

**Comment by J4ckLiu** [comment]
Running spatial-aware conformal prediction (or standard conformal prediction) on your own HSI classifier is really straightforward. Simply place the weights of ANY pre-trained classifier in the appropriate folder and run the code. Be sure to avoid any overlap between the calibration, test, and training sets. You can use the training pipeline of SSTN, available at https://github.com/zilongzhong/SSTN, to train your own classifier.

**Comment by J4ckLiu** [comment]
We have decided to organize our pre-training code and will release it soon.

**Comment by J4ckLiu** [comment]
We have decided to organize and release our pre-training code along with several model weights soon.

**Comment by lijin6** [comment]
I got it .thanks

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 03:05 |
| To | J4ckLiu/SACP ***@***.***> |
| Cc | Rustyoung ***@***.***>,
Author ***@***.***> |
| Subject | Re: [J4ckLiu/SACP] How to download pre-training files. thak you (Issue #1) |

We have decided to organize and release our pre-training code along with several model weights soon.
